server:
  port: 80
  servlet:
    context-path: /eltovdid/
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
spring:
  datasource:
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #jdbc-url: jdbc:log4jdbc:sqlserver://localhost:1433;DatabaseName=eltovdid
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://localhost:1433;DatabaseName=eltovdid
 ## initialization-mode 옵션: never, always (어플리케이션 실행시 sql파일 실행할지 안할지 여부 선택)
    initialization-mode: never
 ## sql 파일 경로
    #schema: classpath:init.sql
    username: sa
    password: skrnl5273@@
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    prefix : classpath:templates/air/web/page/
    suffix : .html
    cache : false
mybatis:
  mapper-locations: classpath:mapper/*.xml
config:
  glUrlRoot: http://10.152.132.150
  glPathRoot: D:/00_FTP_HOME/01_JAVA_HOME/ssh_dp_daejeon_g
  glPathFileRoot: D:/10WEB_HOME/BOOT/PROJECT/eltovDID/src/main/resources/static
  glPathProgram: /zcommonfiles/program
  glSessionTime:  86400
  glCookieTime: 604800
  glFileLimit: 500000000
  glFileLimitImg: 36000000
  glFileLimitMov: 309715200
logging:
  config: classpath:log4j2.xml
---
spring:
  config: 
    activate: 
      on-profile: dev
  datasource:
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #jdbc-url: jdbc:log4jdbc:sqlserver://localhost:1433;DatabaseName=eltovdid
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://localhost:1433;DatabaseName=eltovdid
 ## initialization-mode 옵션: never, always (어플리케이션 실행시 sql파일 실행할지 안할지 여부 선택)
    initialization-mode: never
 ## sql 파일 경로
    #schema: classpath:init.sql
    username: sa
    password: skrnl5273@@
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
config:
  glUrlRoot: http://192.168.0.154
  glPathRoot: D:/10WEB_HOME/BOOT/PROJECT/eltovDID
  glPathFileRoot: D:/10WEB_HOME/BOOT/PROJECT/eltovDID/src/main/resources/static
logging:
  config: classpath:log4j2_dev.xml
  file:
    name: ${user.dir}/log/test.log  # 로깅 파일 위치이다.
    max-history: 1 # 로그 파일 삭제 주기이다. 1일 이후 로그는 삭제한다.
    max-size: 10MB  # 로그 파일 하나당 최대 파일 사이즈이다.